---
title: "Example Document"
author: "Your name here"
output:
  html_document:
    self_contained: true
---

```{r, include=FALSE}
tutorial::go_interactive()
```

By default, `tutorial` will convert all R chunks.

```{r}
a <- 2
b <- 3

a + b
```




```{r ex="create_a", type="pre-exercise-code"}
b <- 5
```

```{r ex="create_a", type="sample-code"}
# Create a variable a, equal to 5


# Print out a

```

```{r ex="create_a", type="solution"}
# Create a variable a, equal to 5
a <- 5

# Print out a
a
```

```{r ex="create_a", type="sct"}
test_object("a")
test_output_contains("a", incorrect_msg = "Make sure to print out `a`.")
success_msg("Great!")
```




```{r ex="create_imp", type="sample-code"}

# carregue o pandas


# Print out imp


```

```{r ex="create_imp", type="solution"}
# Create a variable a, equal to 5
import

# Print out a
imp
```

```{r ex="create_imp", type="sct"}
test_object("imp")
test_output_contains("imp", incorrect_msg = "Make sure to print out `imp`.")
success_msg("Great!")
```


Crie duas variáveis "a" e "b" e atribua valores 3 e 2 a elas

```{r ex="create_a", type="sample-code"}
# Create a variable a, equal to 3


# Create a variable b, equal to 2

```

```{r ex="create_a", type="solution"}
# Create a variable a, equal to 5
a <- 3

# Create a variable a, equal to 5
b <- 2

```

```{r ex="create_a", type="sct"}
test_object("a")
test_output_contains("a", incorrect_msg = "Make sure to print out `a`.")
success_msg("Great!")
```

